const HEADER_NAME_POKEMON = "Pokemon";
const HEADER_NAME_USAGE_PERCENTAGE = "Usage Percentage";
const HEADER_NAME_USAGE_RAW = "Usage Raw";
const HEADER_NAME_USAGE_RAW_PERCENTAGE = "Usage Raw Percentage";
const HEADER_NAME_USAGE_REAL = "Usage Real";
const HEADER_NAME_USAGE_REAL_PERCENTAGE = "Usage Real Percentage";
const HEADER_NAME_RANK = "Rank";

export {
    HEADER_NAME_POKEMON,
    HEADER_NAME_USAGE_PERCENTAGE,
    HEADER_NAME_USAGE_REAL_PERCENTAGE,
    HEADER_NAME_USAGE_REAL,
    HEADER_NAME_USAGE_RAW_PERCENTAGE,
    HEADER_NAME_USAGE_RAW,
    HEADER_NAME_RANK
};
